# Generated by Django 2.2 on 2020-01-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200107_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
