# Generated by Django 2.2 on 2020-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200108_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_product', models.CharField(choices=[('L', 'Laptops'), ('SM', 'Smart phones'), ('T', 'Tablets')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
