# Generated by Django 2.2 on 2020-01-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttags',
            name='tag_product',
        ),
        migrations.AddField(
            model_name='producttags',
            name='tag_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item', unique=True),
        ),
    ]
