# Generated by Django 2.2 on 2020-01-24 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20200119_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(choices=[('Amman', 'Amman'), ('Irbid', 'Irbid'), ('Zarqaa', 'Zarqaa'), ('Aqaba', 'Aqaba'), ('Alkarak', 'Alkarak')], max_length=10)),
                ('07x xxx xxxx', models.PositiveIntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
