# Generated by Django 2.2 on 2020-01-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200124_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='07x xxx xxxx',
        ),
        migrations.AddField(
            model_name='checkoutmodel',
            name='phone_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
